package service

import (
	"context"
	"errors"
	"fmt"
	"log/slog"
	"net/http"
	"strconv"
	"strings"
	"time"

	"github.com/google/uuid"
	"github.com/room-booking/services/availability-service/internal/repository"
)

const SlotGenerationDays = 30

// availRepository is satisfied by *repository.Repository; narrowed for tests.
type availRepository interface {
	CreateSchedule(ctx context.Context, id, roomID uuid.UUID, daysOfWeek []int16, startTime, endTime string) (*repository.Schedule, error)
	GetScheduleByRoomID(ctx context.Context, roomID uuid.UUID) (*repository.Schedule, error)
	GetFreeSlots(ctx context.Context, roomID uuid.UUID, date time.Time) ([]repository.Slot, error)
	GenerateSlots(ctx context.Context, schedule *repository.Schedule, from, until time.Time) (int, error)
	UpsertGenerationState(ctx context.Context, roomID uuid.UUID, until time.Time) error
	GetGenerationState(ctx context.Context, roomID uuid.UUID) (*time.Time, error)
	GetAllSchedules(ctx context.Context) ([]repository.Schedule, error)
	BookSlot(ctx context.Context, slotID, bookingID uuid.UUID) (*repository.SlotMeta, error)
	ReleaseSlot(ctx context.Context, slotID, bookingID uuid.UUID) error
	GetSlotByID(ctx context.Context, slotID uuid.UUID) (*repository.Slot, error)
}

type AvailabilityService struct {
	repo           availRepository
	log            *slog.Logger
	roomServiceURL string
	httpClient     *http.Client
}

func New(repo availRepository, log *slog.Logger, roomServiceURL string) *AvailabilityService {
	return &AvailabilityService{
		repo:           repo,
		log:            log,
		roomServiceURL: roomServiceURL,
		httpClient:     &http.Client{Timeout: 5 * time.Second},
	}
}

type CreateScheduleRequest struct {
	ID         *uuid.UUID `json:"id,omitempty"`
	RoomID     uuid.UUID  `json:"roomId"`
	DaysOfWeek []int      `json:"daysOfWeek"`
	StartTime  string     `json:"startTime"`
	EndTime    string     `json:"endTime"`
}

func (s *AvailabilityService) CreateSchedule(ctx context.Context, pathRoomID uuid.UUID, req CreateScheduleRequest) (*repository.Schedule, error) {
	if req.RoomID != pathRoomID {
		return nil, fmt.Errorf("roomId in body must match path: %w", ErrInvalidRequest)
	}

	// Check room exists
	if err := s.checkRoomExists(ctx, pathRoomID); err != nil {
		return nil, err
	}

	// Validate days
	if len(req.DaysOfWeek) == 0 {
		return nil, fmt.Errorf("daysOfWeek is required: %w", ErrInvalidRequest)
	}
	days := make([]int16, len(req.DaysOfWeek))
	for i, d := range req.DaysOfWeek {
		if d < 1 || d > 7 {
			return nil, fmt.Errorf("daysOfWeek values must be 1-7: %w", ErrInvalidRequest)
		}
		days[i] = int16(d)
	}

	// Validate times
	startTime, err := parseTime(req.StartTime)
	if err != nil {
		return nil, fmt.Errorf("invalid startTime: %w", ErrInvalidRequest)
	}
	endTime, err := parseTime(req.EndTime)
	if err != nil {
		return nil, fmt.Errorf("invalid endTime: %w", ErrInvalidRequest)
	}
	if !endTime.After(startTime) {
		return nil, fmt.Errorf("endTime must be after startTime: %w", ErrInvalidRequest)
	}

	// Check duration divisible by 30
	dur := endTime.Sub(startTime)
	if int(dur.Minutes())%30 != 0 {
		return nil, fmt.Errorf("time range must be divisible by 30 minutes: %w", ErrInvalidRequest)
	}

	scheduleID := uuid.New()
	if req.ID != nil {
		scheduleID = *req.ID
	}

	schedule, err := s.repo.CreateSchedule(ctx, scheduleID, pathRoomID, days, req.StartTime, req.EndTime)
	if err != nil {
		if errors.Is(err, repository.ErrScheduleExists) {
			return nil, ErrScheduleExists
		}
		return nil, err
	}

	// Generate slots for 30 days
	now := time.Now().UTC()
	today := time.Date(now.Year(), now.Month(), now.Day(), 0, 0, 0, 0, time.UTC)
	until := today.AddDate(0, 0, SlotGenerationDays)

	count, err := s.repo.GenerateSlots(ctx, schedule, today, until)
	if err != nil {
		s.log.Error("generate slots failed", "error", err, "roomId", pathRoomID)
		// Schedule created, slots will be generated by worker
	} else {
		s.log.Info("generated slots", "count", count, "roomId", pathRoomID)
	}

	if err := s.repo.UpsertGenerationState(ctx, pathRoomID, until); err != nil {
		s.log.Error("upsert generation state failed", "error", err)
	}

	return schedule, nil
}

func (s *AvailabilityService) GetFreeSlots(ctx context.Context, roomID uuid.UUID, dateStr string) ([]repository.Slot, error) {
	date, err := time.Parse("2006-01-02", dateStr)
	if err != nil {
		return nil, fmt.Errorf("invalid date format: %w", ErrInvalidRequest)
	}

	// Check room exists
	if err := s.checkRoomExists(ctx, roomID); err != nil {
		return nil, err
	}

	// Check if schedule exists
	_, err = s.repo.GetScheduleByRoomID(ctx, roomID)
	if err != nil {
		if errors.Is(err, repository.ErrScheduleNotFound) {
			return []repository.Slot{}, nil
		}
		return nil, err
	}

	slots, err := s.repo.GetFreeSlots(ctx, roomID, date)
	if err != nil {
		return nil, err
	}
	if slots == nil {
		slots = []repository.Slot{}
	}

	// Filter out past slots
	now := time.Now().UTC()
	var filtered []repository.Slot
	for _, slot := range slots {
		if slot.StartAt.After(now) {
			filtered = append(filtered, slot)
		}
	}
	if filtered == nil {
		filtered = []repository.Slot{}
	}
	return filtered, nil
}

func (s *AvailabilityService) ExtendSlots(ctx context.Context) error {
	schedules, err := s.repo.GetAllSchedules(ctx)
	if err != nil {
		return fmt.Errorf("get schedules: %w", err)
	}

	now := time.Now().UTC()
	target := time.Date(now.Year(), now.Month(), now.Day(), 0, 0, 0, 0, time.UTC).AddDate(0, 0, SlotGenerationDays)

	for _, sched := range schedules {
		state, err := s.repo.GetGenerationState(ctx, sched.RoomID)
		if err != nil {
			s.log.Error("get generation state", "error", err, "roomId", sched.RoomID)
			continue
		}

		from := time.Date(now.Year(), now.Month(), now.Day(), 0, 0, 0, 0, time.UTC)
		if state != nil && state.After(from) {
			from = *state
		}

		if !from.Before(target) {
			continue
		}

		count, err := s.repo.GenerateSlots(ctx, &sched, from, target)
		if err != nil {
			s.log.Error("generate slots failed", "error", err, "roomId", sched.RoomID)
			continue
		}

		if err := s.repo.UpsertGenerationState(ctx, sched.RoomID, target); err != nil {
			s.log.Error("upsert generation state", "error", err, "roomId", sched.RoomID)
		}

		if count > 0 {
			s.log.Info("extended slots", "count", count, "roomId", sched.RoomID)
		}
	}
	return nil
}

func (s *AvailabilityService) BookSlot(ctx context.Context, slotID, bookingID uuid.UUID) (*repository.SlotMeta, error) {
	return s.repo.BookSlot(ctx, slotID, bookingID)
}

func (s *AvailabilityService) ReleaseSlot(ctx context.Context, slotID, bookingID uuid.UUID) error {
	return s.repo.ReleaseSlot(ctx, slotID, bookingID)
}

func (s *AvailabilityService) GetSlot(ctx context.Context, slotID uuid.UUID) (*repository.Slot, error) {
	return s.repo.GetSlotByID(ctx, slotID)
}

var (
	ErrInvalidRequest = errors.New("invalid request")
	ErrScheduleExists = errors.New("schedule exists")
	ErrRoomNotFound   = errors.New("room not found")
)

func (s *AvailabilityService) checkRoomExists(ctx context.Context, roomID uuid.UUID) error {
	if s.roomServiceURL == "" {
		return nil // skip check in tests
	}
	req, err := http.NewRequestWithContext(ctx, "GET",
		fmt.Sprintf("%s/internal/rooms/%s", s.roomServiceURL, roomID), nil)
	if err != nil {
		return fmt.Errorf("create room check request: %w", err)
	}
	resp, err := s.httpClient.Do(req)
	if err != nil {
		s.log.Error("room service unavailable", "error", err)
		return fmt.Errorf("room service unavailable: %w", err)
	}
	defer resp.Body.Close()
	if resp.StatusCode == http.StatusNotFound {
		return ErrRoomNotFound
	}
	if resp.StatusCode != http.StatusOK {
		return fmt.Errorf("room service returned %d", resp.StatusCode)
	}
	return nil
}

func parseTime(s string) (time.Time, error) {
	s = strings.TrimSpace(s)
	parts := strings.Split(s, ":")
	if len(parts) != 2 {
		return time.Time{}, fmt.Errorf("invalid time format")
	}
	h, err := strconv.Atoi(parts[0])
	if err != nil || h < 0 || h > 23 {
		return time.Time{}, fmt.Errorf("invalid hour")
	}
	m, err := strconv.Atoi(parts[1])
	if err != nil || m < 0 || m > 59 {
		return time.Time{}, fmt.Errorf("invalid minute")
	}
	return time.Date(0, 1, 1, h, m, 0, 0, time.UTC), nil
}
